"""PLC D 暫存器集中定義。"""

CONVEYOR_FAULT_WORD = 100
CONVEYOR_ACTUAL_SPEED = 101
CONVEYOR_ACTUAL_BUS_CURRENT = 102
CONVEYOR_SET_SPEED_READ = 103
CONVEYOR_ACCEL_READ = 104
CONVEYOR_DECEL_READ = 105
CONVEYOR_BUS_CURRENT_READ = 106
CONVEYOR_PHASE_CURRENT_READ = 107
CONVEYOR_SET_SPEED_WRITE = 108
CONVEYOR_ACCEL_WRITE = 109
CONVEYOR_DECEL_WRITE = 110
CONVEYOR_BUS_CURRENT_WRITE = 111
CONVEYOR_PHASE_CURRENT_WRITE = 112
HMI_CMD_CODE = 1000
HMI_CMD_INDEX = 1001
HMI_CMD_VALID = 1002
HMI_CONVEYOR_SPEED = 1003
HMI_HEARTBEAT_RETURN_INDEX = 1005
PLC_HEARTBEAT_INDEX = 1100
PLC_CMD_ACK_INDEX = 1102
PLC_CMD_RESPONSE_CODE = 1103
PLC_CONVEYOR_STATUS = 1104
HMI_COMM_STATUS = 1105
PLC_STATUS_CODE = 1106
CONVEYOR_TIMEOUT_WORD = 1107
PLC_TO_HMI_SENSOR_STATUS = 1110

CONVEYOR_COMM_TIMEOUT_BIT = 0
CONVEYOR_INITIALIZE_TIMEOUT_BIT = 1

SENSOR_BITS = {
    "bowl_drop_confirm": 0,
    "pause_point_1": 1,
    "pause_point_2": 2,
    "right_stop_point": 3,
    "bowl_dispenser_busy": 4,
}

FAULT_NAMES = (
    "Over Current", "Stall Protection", "Motor Hall Fault", "Motor Fault",
    "Under Voltage", "Over Voltage", "Motor Over Temperature",
    "Controller Over Temperature", "Controller Fault",
)

PARAMETER_LIMITS = {
    "Speed RPM": (100, 1000),
    "Acceleration": (5, 50),
    "Deceleration": (5, 50),
    "Bus Current Setting": (0, 65535),
    "Phase Current Setting": (0, 65535),
}
